apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/creatorId: user-zmzvw
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.7.222"],"port":4971,"protocol":"TCP","serviceName":"default:burp-loadbalancer","allNodes":false}]'
  creationTimestamp: "2020-02-22T22:14:31Z"
  generation: 4
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-burp
  name: burp
  namespace: default
  resourceVersion: "471710"
  selfLink: /apis/apps/v1/namespaces/default/deployments/burp
  uid: 1bbb6972-992d-460c-9a51-9d9da4d97ac4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-burp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-02-22T22:12:33Z"
        field.cattle.io/ports: '[[{"containerPort":4971,"dnsName":"burp","hostPort":0,"kind":"ClusterIP","name":"burp","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-burp
    spec:
      containers:
      - image: registry.localdomain:5000/burp:2020-02-21
        imagePullPolicy: Always
        name: burp
        ports:
        - containerPort: 4971
          name: burp
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /etc/burp
          name: burp-config-pvc
        - mountPath: /var/spool/burp
          name: burp-data-pvc
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: burp-config-pvc
        persistentVolumeClaim:
          claimName: burp-config
      - name: burp-data-pvc
        persistentVolumeClaim:
          claimName: burp-data
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-02-22T22:14:31Z"
    lastUpdateTime: "2020-02-22T22:15:13Z"
    message: ReplicaSet "burp-5b6f496777" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-02-22T22:20:11Z"
    lastUpdateTime: "2020-02-22T22:20:11Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
