apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
  creationTimestamp: "2020-02-20T20:39:04Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: iot-api
  namespace: default
  resourceVersion: "10878"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/iot-api
  uid: 9529d8c2-9afd-446c-a11e-1b52b901aff0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: longhorn-static
  volumeMode: Filesystem
  volumeName: iot-api
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 512Mi
  phase: Bound
