apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    field.cattle.io/creatorId: user-zmzvw
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.7.226"],"port":80,"protocol":"TCP","serviceName":"default:iot-api-loadbalancer","allNodes":false}]'
  creationTimestamp: "2020-02-20T20:41:01Z"
  generation: 3
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-iot-api
  name: iot-api
  namespace: default
  resourceVersion: "15418"
  selfLink: /apis/apps/v1/namespaces/default/deployments/iot-api
  uid: 8d44a03a-f4fd-471b-8807-530e6cc92a99
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-iot-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-02-20T20:43:53Z"
        field.cattle.io/ports: '[[{"containerPort":80,"dnsName":"iot-api","hostPort":0,"kind":"ClusterIP","name":"80tcp02","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-iot-api
    spec:
      containers:
      - image: registry.localdomain:5000/iot-api:2020-02-13
        imagePullPolicy: Always
        name: iot-api
        ports:
        - containerPort: 80
          name: 80tcp02
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /opt/data
          name: iot-api-pvc
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: iot-api-pvc
        persistentVolumeClaim:
          claimName: iot-api
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-02-20T20:41:22Z"
    lastUpdateTime: "2020-02-20T20:41:22Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-02-20T21:04:58Z"
    lastUpdateTime: "2020-02-20T21:04:59Z"
    message: ReplicaSet "iot-api-75c7ccc74" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
