apiVersion: v1
data:
  main-nginx.conf: "server {\n    listen 80;\n    return 301 https://$host$request_uri;\n}\n\nserver
    {\n    server_name  brandongant.com;\n\n    location / {\n        root   /var/lib/nginx/html;\n
    \       index  index.html index.htm;\n    }\n\n    #error_page  404              /404.html;\n\n
    \   # redirect server error pages to the static page /50x.html\n    error_page
    \  500 502 503 504  /50x.html;\n    location = /50x.html {\n        root   /var/lib/nginx/html;\n
    \   }\n\n    # iot-api redirects\n    location /update {\n        proxy_set_header
    Host $host;\n        proxy_set_header X-Real-IP $remote_addr;\n        proxy_pass
    http://192.168.7.100:8001/update;\n    }\n    location /channels {              \n
    \       proxy_set_header Host $host;            \n        proxy_set_header X-Real-IP
    $remote_addr;    \n        proxy_pass http://192.168.7.100:8001/channels;\n    }\n\n
    \   listen 443 ssl; # managed by Certbot\n    ssl_certificate /etc/letsencrypt/live/brandongant.com/fullchain.pem;
    # managed by Certbot\n    ssl_certificate_key /etc/letsencrypt/live/brandongant.com/privkey.pem;
    # managed by Certbot\n    include /etc/letsencrypt/options-ssl-nginx.conf; # managed
    by Certbot\n    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot\n\n
    \   # Source: https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-debian-8\n
    \   # Source: https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html\n
    \   # Source: https://cipherli.st/\n    #ssl_ciphers EECDH+AESGCM:EDH+AESGCM;
    # handled above by Certbot options-ssl-nginx.conf\n    ssl_ecdh_curve secp384r1;
    # Requires nginx >= 1.1.0\n    ssl_stapling on; # Requires nginx >= 1.3.7\n    ssl_stapling_verify
    on; # Requires nginx => 1.3.7\n    resolver 1.1.1.1 valid=300s;\n    resolver_timeout
    5s; \n    #add_header Strict-Transport-Security \"max-age=63072000; includeSubDomains;
    preload\";  # preload has consequences\n    add_header Strict-Transport-Security
    \"max-age=63072000; includeSubdomains\";\n    add_header X-Frame-Options DENY;\n
    \   add_header X-Content-Type-Options nosniff;\n    add_header X-XSS-Protection
    \"1; mode=block\";\n}"
kind: ConfigMap
metadata:
  annotations:
    field.cattle.io/creatorId: user-zmzvw
  creationTimestamp: "2020-03-04T18:57:56Z"
  labels:
    cattle.io/creator: norman
  name: main-nginx-config
  namespace: default
  resourceVersion: "2899317"
  selfLink: /api/v1/namespaces/default/configmaps/main-nginx-config
  uid: d1ba6f7c-a8c2-4fd0-961d-e944aac67bbe
