apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/creatorId: user-zmzvw
    field.cattle.io/ipAddresses: "null"
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.7.225"],"port":80,"protocol":"TCP","serviceName":"default:main-nginx-loadbalancer","allNodes":false},{"addresses":["192.168.7.225"],"port":443,"protocol":"TCP","serviceName":"default:main-nginx-loadbalancer","allNodes":false}]'
    field.cattle.io/targetDnsRecordIds: "null"
    field.cattle.io/targetWorkloadIds: '["deployment:default:main-nginx"]'
  creationTimestamp: "2020-02-20T21:30:57Z"
  labels:
    cattle.io/creator: norman
  name: main-nginx-loadbalancer
  namespace: default
  resourceVersion: "20573"
  selfLink: /api/v1/namespaces/default/services/main-nginx-loadbalancer
  uid: 3741a6be-62ce-486c-b324-da8020610aae
spec:
  clusterIP: 10.43.11.214
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.7.225
  ports:
  - name: http
    nodePort: 30254
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 31026
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    workloadID_main-nginx-loadbalancer: "true"
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.7.225
